@TRACING_TEST_ENDPOINT = localhost:8080

###

GET http://{{TRACING_TEST_ENDPOINT}}/jpa/country/1

###

PUT http://{{TRACING_TEST_ENDPOINT}}/jpa/country/2
Content-Type: application/x-www-form-urlencoded

name=XXX

###

POST http://{{TRACING_TEST_ENDPOINT}}/tracing/invoke
Content-Type: application/json

[
    {
        "endpoint" : "http://helidon-mp-demo-1:8080/tracing/invoke",
        "orders" : []
    },
    {
      "endpoint" : "http://helidon-mp-demo-2:8080/tracing/invoke",
        "orders" : [
            {
                "endpoint" : "http://helidon-mp-demo-3:8080/tracing/invoke",
                "orders" : [
                    {
                        "endpoint" : "http://helidon-mp-demo-1:8080/tracing/invoke",
                        "orders" : []
                    }
                ]
            },
            {
                "endpoint" : "http://helidon-mp-demo-0:8080/tracing/invoke",
                "orders" : []
            }
        ]
    }
]

### test local

POST http://{{TRACING_TEST_ENDPOINT}}/tracing/invoke
Content-Type: application/json

[
    {
        "endpoint" : "http://localhost:8080/tracing/invoke",
        "orders" : []
    },
    {
      "endpoint" : "http://localhost:8080/tracing/invoke",
        "orders" : [
            {
                "endpoint" : "http://localhost:8080/tracing/invoke",
                "orders" : [
                    {
                        "endpoint" : "http://localhost:8080/tracing/invoke",
                        "orders" : []
                    }
                ]
            },
            {
                "endpoint" : "http://localhost:8080/tracing/invoke",
                "orders" : []
            }
        ]
    }
]

###


