-- alter session set container PDB1

CREATE USER DEMO IDENTIFIED BY "OCHaCafe6666" DEFAULT TABLESPACE users TEMPORARY TABLESPACE temp;

GRANT RESOURCE, CONNECT TO DEMO;

GRANT UNLIMITED TABLESPACE TO DEMO;

DROP TABLE DEMO.GREETING;
CREATE TABLE DEMO.GREETING (
    SALUTATION VARCHAR(64) NOT NULL PRIMARY KEY,
    RESPONSE VARCHAR(64) NOT NULL
);

INSERT INTO DEMO.GREETING (SALUTATION, RESPONSE) VALUES ('Marco', 'Polo');

DROP TABLE DEMO.COUNTRY;
CREATE TABLE DEMO.COUNTRY (
    COUNTRY_ID NUMBER NOT NULL PRIMARY KEY,
    COUNTRY_NAME VARCHAR(64) NOT NULL
);

INSERT INTO DEMO.COUNTRY (COUNTRY_ID, COUNTRY_NAME) VALUES ('1', 'USA');
INSERT INTO DEMO.COUNTRY (COUNTRY_ID, COUNTRY_NAME) VALUES ('81', 'Japan');

COMMIT;

SELECT * FROM DEMO.GREETING;
SELECT * FROM DEMO.COUNTRY;

EXIT;