CREATE TABLE IF NOT EXISTS GREETING (
    SALUTATION VARCHAR(64) NOT NULL PRIMARY KEY,
    RESPONSE VARCHAR(64) NOT NULL
);

MERGE INTO GREETING (SALUTATION, RESPONSE) VALUES ('Marco', 'Polo');

CREATE TABLE IF NOT EXISTS COUNTRY (
    COUNTRY_ID NUMBER NOT NULL PRIMARY KEY,
    COUNTRY_NAME VARCHAR(64) NOT NULL
);

MERGE INTO COUNTRY (COUNTRY_ID, COUNTRY_NAME) VALUES ('1', 'USA');
MERGE INTO COUNTRY (COUNTRY_ID, COUNTRY_NAME) VALUES ('81', 'Japan');


